// Global constants for the frontend application

export const ACCENT_CYAN = "#00bcd4";

export const SG_DISTRICTS = [
  "Ang Mo Kio",
  "Bedok",
  "Bishan",
  "Bukit Batok",
  "Bukit Merah",
  "Bukit Panjang",
  "Bukit Timah",
  "Central Area",
  "Choa Chu Kang",
  "Clementi",
  "Geylang",
  "Hougang",
  "Jurong East",
  "Jurong West",
  "Kallang",
  "Marine Parade",
  "Pasir Ris",
  "Punggol",
  "Queenstown",
  "Sembawang",
  "Sengkang",
  "Serangoon",
  "Tampines",
  "Toa Payoh",
  "Woodlands",
  "Yishun",
  "Simei",
];

export const FIELD_NAME_SUGGESTIONS = [
  "Baptism Date",
  "Cell Group",
  "Role",
  "Notes",
  "Emergency Contact",
];

export const RELATION_SUGGESTIONS = [
  "Father",
  "Mother",
  "Son",
  "Daughter",
  "Brother",
  "Sister",
  "Husband",
  "Wife",
  "Grandfather",
  "Grandmother",
  "Grandson",
  "Granddaughter",
  "Father-in-law",
  "Mother-in-law",
  "Son-in-law",
  "Daughter-in-law",
  "Brother-in-law",
  "Sister-in-law",
  "Uncle",
  "Aunt",
  "Cousin",
  "Friend",
  "Colleague",
  "Spouse",
];

export const RELATION_INVERSE_MAP = {
  father: "Child",
  mother: "Child",
  son: "Parent",
  daughter: "Parent",
  brother: "Sibling",
  sister: "Sibling",
  husband: "Wife",
  wife: "Husband",
  grandfather: "Grandchild",
  grandmother: "Grandchild",
  grandson: "Grandparent",
  granddaughter: "Grandparent",
  "father-in-law": "Child-in-law",
  "mother-in-law": "Child-in-law",
  "parent-in-law": "Child-in-law",
  "son-in-law": "Parent-in-law",
  "daughter-in-law": "Parent-in-law",
  "child-in-law": "Parent-in-law",
  "brother-in-law": "Sibling-in-law",
  "sister-in-law": "Sibling-in-law",
  "sibling-in-law": "Sibling-in-law",
  uncle: "Niece/Nephew",
  aunt: "Niece/Nephew",
  cousin: "Cousin",
  friend: "Friend",
  colleague: "Colleague",
  spouse: "Spouse",
};

export const RELATION_AUTO_RECIPROCALS = {
  husband: "Wife",
  wife: "Husband",
  friend: "Friend",
  colleague: "Colleague",
  spouse: "Spouse",
  "father-in-law": "Child-in-law",
  "mother-in-law": "Child-in-law",
  "parent-in-law": "Child-in-law",
  "son-in-law": "Parent-in-law",
  "daughter-in-law": "Parent-in-law",
  "child-in-law": "Parent-in-law",
  "brother-in-law": "Sibling-in-law",
  "sister-in-law": "Sibling-in-law",
  "sibling-in-law": "Sibling-in-law",
};

export const RELATION_RECIPROCAL_SUGGESTIONS = {
  father: ["Son", "Daughter"],
  mother: ["Son", "Daughter"],
  son: ["Father", "Mother"],
  daughter: ["Father", "Mother"],
  grandfather: ["Grandchild"],
  grandmother: ["Grandchild"],
  grandson: ["Grandparent"],
  granddaughter: ["Grandparent"],
  "father-in-law": ["Son-in-law", "Daughter-in-law"],
  "mother-in-law": ["Son-in-law", "Daughter-in-law"],
  "parent-in-law": ["Son-in-law", "Daughter-in-law"],
  "son-in-law": ["Father-in-law", "Mother-in-law"],
  "daughter-in-law": ["Father-in-law", "Mother-in-law"],
  "child-in-law": ["Father-in-law", "Mother-in-law"],
  "brother-in-law": ["Brother-in-law", "Sister-in-law"],
  "sister-in-law": ["Brother-in-law", "Sister-in-law"],
  "sibling-in-law": ["Brother-in-law", "Sister-in-law"],
  uncle: ["Niece", "Nephew"],
  aunt: ["Niece", "Nephew"],
  husband: ["Wife"],
  wife: ["Husband"],
  spouse: ["Spouse"],
  brother: ["Brother", "Sister"],
  sister: ["Brother", "Sister"],
  friend: ["Friend"],
  colleague: ["Colleague"],
};
